name: Build

on: [push, pull_request]

jobs:
    windows:
        runs-on: windows-2022

        steps:
        - uses: actions/checkout@v2
        - uses: open-watcom/setup-watcom@v0
        - run: |
            SET LIB386_PATH=%CD%\LIB386
            SET INCLUDE=%LIB386_PATH%;%INCLUDE%
            cd LIB386\LIB_3D
            wmake
            cd ..\LIB_CD
            wmake
            cd ..\LIB_MENU
            wmake
            cd ..\LIB_MIDI
            wmake
            cd ..\LIB_MIX
            wmake
            cd ..\LIB_SAMP
            wmake
            cd ..\LIB_SVGA
            wmake
            cd ..\LIB_SYS
            wmake
            cd ..\..\SOURCES
            wmake
            link

        - name: Upload the build artifacts
          uses: actions/upload-artifact@v2
          with:
            name: lba1
            path: SOURCES/LBA0.exe
